---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-test-pod
  namespace: openshift-storage
  labels:
    app: nfs-test-pod
spec:
  selector:
    matchLabels:
      name: nfs-test-pod
  replicas: 1
  template:
    metadata:
      labels:
        name: nfs-test-pod
    spec:
      restartPolicy: Always
      volumes:
      - name: vol
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: fedora
        image: fedora
        command: ['/bin/bash', '-ce', 'tail -f /dev/null']
        imagePullPolicy: IfNotPresent
        securityContext:
          capabilities: {}
          privileged: true
        volumeMounts:
        - mountPath: /mnt
          name: vol
        livenessProbe:
          exec:
            command:
            - 'sh'
            - '-ec'
            - 'df /mnt'
          initialDelaySeconds: 3
          periodSeconds: 3
  paused: false

